Add `csexec-loader` for aarch64
csutils/cswrap pull request #9
Opened 2022-03-02 12:28 UTC by lzaoral

2022-03-02 12:43 UTC, lzaoral commented on src/csexec-loader-aarch64.c
> +    // read argc/argv from stack (System V AMD64 ABI: Process Initialization)
Oh, I forgot to change this line.

2022-03-07 11:50 UTC, kdudka requested changes
Nice work.  Two minor comments inline.

2022-03-07 12:06 UTC, kdudka commented on make-srpm.sh
> +%ifarch aarch64 x86_64
I meant something like this:
```diff
--- a/make-srpm.sh
+++ b/make-srpm.sh
@@ -72,6 +72,13 @@ xz -c "$SRC_TAR" > "$SRC"               || die "failed to compress sources"

 SPEC="$TMP/$PKG.spec"
 cat > "$SPEC" << EOF
+%ifarch %{ix86} x86_64
+# csexec is available on aarch64 and x86_64 only for now
+%bcond_without csexec
+%else
+%bcond_with csexec
+%endif
+
 Name:       $PKG
 Version:    $VER
 Release:    1%{?dist}
@@ -114,8 +121,7 @@ BuildRequires: glibc-static
 %description
 Generic compiler wrapper used by csmock to capture diagnostic messages.

-# csexec is available on aarch64 and x86_64 only for now
-%ifarch aarch64 x86_64
+%if %{with csexec}
 %package -n csexec
 Summary: Dynamic linker wrapper
 Conflicts: csexec < %{version}-%{release}
@@ -161,7 +167,7 @@ done
 %{_mandir}/man1/%{name}.1*
 %doc COPYING README

-%ifarch x86_64
+%if %{with csexec}
 %files -n csexec
 %{_bindir}/csexec
 %{_bindir}/csexec-loader
```
... but we would also need to introduce a CMake option for it to make it actually work as expected.  It might be not worth the effort.  Still it would be good to keep the list of supported arches on a single place.

2022-03-08 13:17 UTC, lzaoral commented on src/CMakeLists.txt
> +    target_compile_definitions(csexec PRIVATE LD_LINUX_SO="${LD_LINUX_SO}")
Done in d2945424892b3b07bbd3cbbbad2ac2ac5931ed29.

2022-03-08 13:51 UTC, kdudka commented on src/CMakeLists.txt
> +    target_compile_definitions(csexec PRIVATE LD_LINUX_SO="${LD_LINUX_SO}")
Thanks!

2022-03-08 13:55 UTC, kdudka approved these changes

2022-03-08 16:14 UTC, lzaoral commented
654b3da4e3ba4bd8b8d473b6c4f6f672fde1fe4c did not cause any regressions on aarch64, x86_64 and ppc64le and actually fixes the auxiliary vector traversal on s390x! (PRs with ppc64le and s390x will be published shortly.)

2022-03-10 14:11 UTC, lzaoral commented
CI is finally green and `./make_srpm.sh` produces a SRPM that can be successfully built using `mock` botn on aarch64 and x86_64. So this PR is ready for a review, @kdudka. Thanks in advance!

2022-03-10 17:42 UTC, lzaoral commented
The [ppc64le](https://github.com/lzaoral/cswrap/tree/ppc64le) and [s390x](https://github.com/lzaoral/cswrap/tree/s390x) changes are ready as well.  They depend on changes introduced in this PR, though, so I'll create the corresponding PRs later.

2022-03-11 10:02 UTC, kdudka requested changes
We need to build the package in `epel-7-x86_64` buildroot because it is used by Covscan.  I think we can just skip the csexec tests based on some compatibility check?

2022-03-16 15:53 UTC, lzaoral commented on src/csexec-loader-aarch64.c
> +#include "csexec-loader-common.c"
Resolved in e4600f6 and f79e341.

2022-03-16 15:54 UTC, lzaoral commented
/packit build

2022-03-16 16:05 UTC, kdudka approved these changes
Looks perfect.

2022-03-22 08:26 UTC, lzaoral commented
The last rebase did not contain any new changes so I'm merging it.

2022-03-22 08:29 UTC, merged